
# Netlify configuration file

[build]
  # Directory where the build command will be run
  base = "/"
  
  # Command to build your site
  command = "npm run build"
  
  # Directory with the built files that will be deployed
  publish = "dist"

# Production context: Environment variables for the production branch
[context.production.environment]
  NODE_VERSION = "18"
